/* ****************************************************************************************
 * Faculdade de Engenharias Arquitetura e Urbanismo (FEAU) (Univap)
 * Curso: Engenharia da Computação - Data de Entrega: 29/05/2023
 * Autor: Heloan José Jacinto Marinho
 * Autor: Pedro Henrique Serpa Bechelli
 *
 * Turma: 7UNA Disciplina: Algoritmos Estrutura de Dados - II
 * Projeto Final - E referente ao 2 - Bimestre
 * ***************************************************************************************/

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.CodeSource;
import java.security.ProtectionDomain;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.Timer;

public class TelaJogo extends javax.swing.JPanel {

    // Implementa uma lista de botões que serão os cards do jogo.
    public static ListaLigadaDupla _buttonList = new ListaLigadaDupla();
    
    // Atributos do jogo.
    private JButton _card = null;
    private int _qntDeTentativas = 0;
    private int _maxQnt;
    private int _combinacoes;
    private String _level;
    private String _player;
    private String[] _animal = {"elefante", "galinha", "girafa", "leao", 
        "macaco", "onca", "peixe", "rinoceronte", "urso", "zebra"};
    
    /**
     * Creates new form Jogo
     */
    public TelaJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloNivel = new javax.swing.JLabel();
        cboNivel = new javax.swing.JComboBox();
        btnJogar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();

        lblTituloNivel.setText("Escolha o Nivel");

        cboNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Facil", "Medio", "Dificil" }));

        btnJogar.setText("Jogar");
        btnJogar.setName("teste"); // NOI18N
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        lblNome.setText("Jogador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(156, 156, 156))
                    .addComponent(txtNome))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJogar)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Ação iniciar o jogo
    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        if(!txtNome.getText().trim().isEmpty()){

            // Prepar jogo:
            this._level = cboNivel.getSelectedItem().toString();
            this._player = txtNome.getText();
            lblTituloNivel.setVisible(false);
            cboNivel.setVisible(false);
            btnJogar.setVisible(false);
            lblNome.setVisible(false);
            txtNome.setVisible(false);

            // Load game
            this.loadGame();

        }
    }//GEN-LAST:event_btnJogarActionPerformed

    // Carrega os cards.
    private void loadGame(){
        // Quantidade de items
        int countButtons;
        if(this._level == "Facil"){
            countButtons = 6;
            this._maxQnt = 9;
            this._combinacoes = 3;
        }
        else if(this._level == "Medio"){
            countButtons = 16;
            this._maxQnt = 24;
            this._combinacoes = 8;
        }
        else {
            countButtons = 20;
            this._maxQnt = 30;
            this._combinacoes = 10;
        }

        // Criar os botões
        // Lista index serve para filtrar os index de animais, que já foram vinculados a um animal.
        ListaLigadaDupla indexOptions = new ListaLigadaDupla();  
        for(int i=0; i<countButtons; i++){            
            int index = Recursos.geradorAleatrioDeNumero(0, (countButtons/2) - 1, indexOptions);
            indexOptions.adiciona(index);
            JButton botao = new JButton("Card");
            botao.setPreferredSize(new Dimension(110, 110));
            botao.setName(_animal[index]);
            TelaJogo._buttonList.adiciona(botao);
        }

        // Configurar layout grid.
        JPanel painelBotoes;
        if(this._level == "Facil")
            painelBotoes = new JPanel(new GridLayout(3, 2));
        else if(this._level == "Medio")
            painelBotoes = new JPanel(new GridLayout(4, 4));
        else
            painelBotoes = new JPanel(new GridLayout(5, 4));

        // Adicionar os botões ao painel
        for(int i=0; i<countButtons; i++){
            JButton botao = (JButton) TelaJogo._buttonList.pega(i);
            painelBotoes.add(botao);
            
            botao.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnCardActionPerformed(e);
                }
            });
        }

        // Adicionar o painel ao JFrame
        this.setLayout(new BorderLayout());
        this.add(painelBotoes, BorderLayout.CENTER);
    }
      
    // Implementa a interação do jogo com as cartas.
    private void btnCardActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            JButton button = (JButton) evt.getSource();
            String animal = button.getName();
            if(button != this._card && animal != ""){
                
                // adicionar imagem do card
                button.setText(animal);
                button.setIcon(new ImageIcon(animal + ".png"));

                if(this._card == null)
                    this._card = button;
                else if(this._card.getName() != animal){
                    this._card = null;
                    this._qntDeTentativas++;
                    this.hideCards();
                }
                else {
                    this._combinacoes--;
                    this._qntDeTentativas++;
                    this._card.setName("");
                    button.setName("");
                    this._card = null;
                    if(this._combinacoes == 0)
                        this.gameOver();
                }
            }
        }catch (Exception ex) {
          System.out.println(ex);
        }
    }
    
    // Emcerra o jogo
    private void gameOver(){
        for(int i=0; i<TelaJogo._buttonList.tamanho(); i++){
            JButton botao = (JButton)TelaJogo._buttonList.pega(i);
            botao.setVisible(false);
        }
        
        Jogador jogador = new Jogador(this._player, (this._maxQnt + 1) - this._qntDeTentativas);
        TelaPrincipal.ranking.add(jogador);
        lblTituloNivel.setVisible(true);
        lblTituloNivel.setText(jogador.getNome() + " fez " + jogador.getPontos() + " pontos!");
    }
    
    // esconde os cards
    private void hideCards(){
        this.lock();
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                for(int i=0; i<TelaJogo._buttonList.tamanho(); i++){
                    JButton botao = (JButton) TelaJogo._buttonList.pega(i);  
                    botao.setEnabled(true);
                    if(botao.getName() != ""){
                        botao.setText("Card");
                        botao.setIcon(null);
                    }
                }
            }
        });

        timer.setRepeats(false); // Execute only once
        timer.start(); 
    }
    
    // Impede que os cards sejão clicados
    private void lock(){
        for(int i=0; i<TelaJogo._buttonList.tamanho(); i++){
            JButton botao = (JButton)TelaJogo._buttonList.pega(i);
            botao.setEnabled(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JComboBox cboNivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTituloNivel;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
